package handongplay3.Admin;

import java.sql.Statement ;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;

import com.mysql.jdbc.PreparedStatement;

import handongplay2.Storage.Storage;

public class Enroll extends javax.swing.JFrame {

	
	
			
	
	

   /**
    * Creates new form Enroll
    */
   public Enroll() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jTextField1 = new javax.swing.JTextField();
       jTextField2 = new javax.swing.JTextField();
       jTextField3 = new javax.swing.JTextField();
       jTextField4 = new javax.swing.JTextField();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       jLabel5 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jLabel3 = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jTextField3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField3ActionPerformed(evt);
           }
       });

       jLabel1.setText("제목");

       jLabel2.setText("극단");

       jLabel4.setText("내용");

       jLabel5.setText("날짜");

       jButton1.setText("등록");
       
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               try {
				jButton1ActionPerformed(evt);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
           }
       });

       jLabel3.setText("연극정보등록");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(48, 48, 48)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                   .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                   .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTextField3))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(118, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jLabel3)
                       .addGap(132, 132, 132))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(101, 101, 101))))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(27, 27, 27)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel2))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel5))
               .addGap(7, 7, 7)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel4))
               .addGap(28, 28, 28)
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(28, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>                        

   private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           
//////////////////////////////////////등록버튼 눌렀을때//////////////////////////////////
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                         
	   
	   
	 //==============================================//
	   			Connection con = null;
	   			
	   			
		
	   			try {
	   							Class.forName("com.mysql.jdbc.Driver").newInstance();
	   				} catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
	   						// TODO Auto-generated catch block
	   						e.printStackTrace();
	   				}
	   			try {
	   								con = DriverManager.getConnection("jdbc:mysql://localhost", "root", "12skdmsdn");
	   				} catch (SQLException e) {
	   						// TODO Auto-generated catch block
	   						e.printStackTrace();
	   						}
	   				try {
	   						if (!con.isClosed())
	   								System.out.println("Successfully connected to MySQL server.");
	   					} catch (SQLException e) {
	   							// TODO Auto-generated catch block
	   								e.printStackTrace();
	   								}
		
	   										Statement stmt = null;
	   											try {
	   													stmt = (Statement) con.createStatement();
	   												} catch (SQLException e) {
	   														// TODO Auto-generated catch block
	   													e.printStackTrace();
	   												}
	   												try {
	   															stmt.execute("use playinfo") ;
	   													} catch (SQLException e) {
	   															// TODO Auto-generated catch block
	   															e.printStackTrace();
	   														}
//===============================================//   
	   
/////////////////////////////////////////////////////////////////////////////////////////////////////////       
	   												Storage pi = new Storage(); 
       
	   												PreparedStatement s = (PreparedStatement) con.prepareStatement("INSERT INTO playinfo(title,player,date,content) VALUES(?,?,?,?)");
	   												System.out.print(jTextField1.getText());
	   												s.setString(1, jTextField1.getText());
	   												s.setString(2, jTextField2.getText());
	   												s.setString(3, jTextField4.getText());
	   												s.setString(4, jTextField3.getText());
	   												s.executeUpdate();
	   												
	   												s.close();
	   												
	   												//등록 버튼 눌렀을때 
	   												setVisible(false); //그냥 setVisible 해준다~~
   }                                        
  
   
   
   
   
   
   /**
    * @param args the command line arguments
    */
   public void Start() {

       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
           //    new Enroll().setVisible(true);
               
               new Enroll().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextField jTextField4;
   // End of variables declaration                   
}
