package handongplay3.Admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import handongplay3.Storage.Storage;
import handongplay3.User.HandongPlay;






@SuppressWarnings("serial")
public class ManagePlay extends javax.swing.JFrame {

	public static String ccPlay="";
	Connection con = null;
	Statement stmt = null;	
	
	
    public ManagePlay() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()throws SQLException {

    	

    	
   	   			
   		
   	   			try {
   	   							Class.forName("com.mysql.jdbc.Driver").newInstance();
   	   				} catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
   	   						// TODO Auto-generated catch block
   	   						e.printStackTrace();
   	   				}
   	   			try {
   	   								con = DriverManager.getConnection("jdbc:mysql://localhost?autoReconnect=true&useSSL=false", "root", "12skdmsdn");
   	   				} catch (SQLException e) {
   	   						// TODO Auto-generated catch block
   	   						e.printStackTrace();
   	   						}
   	   				try {
   	   						if (!con.isClosed())
   	   								System.out.println("Successfully connected to MySQL server.");
   	   					} catch (SQLException e) {
   	   							// TODO Auto-generated catch block
   	   								e.printStackTrace();
   	   								}
   		
   	   									
   	   											try {
   	   													stmt = (Statement) con.createStatement();
   	   												} catch (SQLException e) {
   	   														// TODO Auto-generated catch block
   	   													e.printStackTrace();
   	   												}
   	   												try {
   	   															stmt.execute("use playinfo") ;
   	   													} catch (SQLException e) {
   	   															// TODO Auto-generated catch block
   	   															e.printStackTrace();
   	   														}
   //===============================================//   
   	   							Storage [] pi = new Storage[7];
   	   							
   	   						 for( int i = 0; i < 7 ; i++)
	   						    {
   	   							 	pi[i] = new Storage();
	   					
	   						    }
   	   			
   	   							stmt.executeQuery("SELECT title,player,date,content FROM playinfo");
   	   						    ResultSet rs = stmt.getResultSet(); 		
   	   						
    	    				
    	    				
   	   						   
   	   						    for( int i = 0; rs.next() ; i++)
   	   						    {
   	   						    	pi[i].get_title(rs.getString("title"));
   	   						    	pi[i].get_player(rs.getString("player"));
   	   						    	pi[i].get_date(rs.getString("date"));
   	   						    	pi[i].get_content(rs.getString("content"));
   	   						    }
   	   						    
   	   						    rs.close();

        Choice = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        cancelList = new javax.swing.JComboBox<>();

        String item1 = pi[0].return_title()+"/"+pi[0].return_player()+"/"+pi[0].return_date()+"/"+pi[0].return_content();
        String item2 = pi[1].return_title()+"/"+pi[1].return_player()+"/"+pi[1].return_date()+"/"+pi[1].return_content();
        String item3 = pi[2].return_title()+"/"+pi[2].return_player()+"/"+pi[2].return_date()+"/"+pi[2].return_content();
        String item4 = pi[3].return_title()+"/"+pi[3].return_player()+"/"+pi[3].return_date()+"/"+pi[3].return_content();
        String item5 = pi[4].return_title()+"/"+pi[4].return_player()+"/"+pi[4].return_date()+"/"+pi[4].return_content();
        String item6 = pi[5].return_title()+"/"+pi[5].return_player()+"/"+pi[5].return_date()+"/"+pi[5].return_content();
        String item7 = pi[6].return_title()+"/"+pi[6].return_player()+"/"+pi[6].return_date()+"/"+pi[6].return_content();
        
        Choice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        Choice.setToolTipText("");
        Choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoiceActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {"1",pi[0].return_title(),pi[0].return_player(),pi[0].return_date(),pi[0].return_content()},
                {"2",pi[1].return_title(),pi[1].return_player(),pi[1].return_date(),pi[1].return_content()},
                {"3",pi[2].return_title(),pi[2].return_player(),pi[2].return_date(),pi[2].return_content()},
                {"4",pi[3].return_title(),pi[3].return_player(),pi[3].return_date(),pi[3].return_content()},
                {"5",pi[4].return_title(),pi[4].return_player(),pi[4].return_date(),pi[4].return_content()},
                {"6",pi[5].return_title(),pi[5].return_player(),pi[5].return_date(),pi[5].return_content()},
                {"7",pi[6].return_title(),pi[6].return_player(),pi[6].return_date(),pi[6].return_content()},
                {null, null, null, null, null}
            },
            new String [] {
                "idx", "Title", "Player", "Date", "Content"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("등록");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelBtn.setText("삭제");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					cancelBtnActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        cancelList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { item1, item2,item3,item4,item5,item6,item7 }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cancelList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cancelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       Enroll enroll = new Enroll();
       enroll.Start();
       
    }                                        

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                          
        ccPlay =   cancelList.getSelectedItem().toString();
        
    	String []str_arr = ccPlay.split("/");
    	
    	//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@2
    	//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    	//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@예약취소 부분!!!
    	stmt = (Statement) con.createStatement();
    	int r = stmt.executeUpdate("delete from playinfo where "+"title = "+"\'"+str_arr[0]+"\'"+"and player = "+"\'"+str_arr[1]+"\'"+"and date = "+"\'"+str_arr[2]+"\'"+"and content = "+"\'"+str_arr[3]+"\'");
    	
    	if( r == 0)
    	{
    		JOptionPane.showMessageDialog(null, "삭제할 데이터를 찾지 못했습니다.");
    	}
    	
    	
    	
    	
    	
    	JOptionPane.showMessageDialog(null, "연극 정보가 삭제되었습니다.");
    	this.setVisible(false);
    	new AdminPlay().setVisible(true);;
    }                                         

    private void ChoiceActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

   
    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> Choice;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> cancelList;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
