
package handongplay3.User;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


import handongplay3.Storage.Storage;
import handongplay3.iterator.Iterator;
import handongplay3.iterator.*;
/**
 *
 * @author pv17
 */
@SuppressWarnings("serial")
public class PlayInfo extends javax.swing.JFrame {

	
			static String bookinginfo;
    /**
     * Creates new form PlayInfo
     * @throws SQLException 
     */
    public PlayInfo() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()  throws SQLException {
    	
    	
    	Connection con = null;
  			
  			
   		
  			try {
  							Class.forName("com.mysql.jdbc.Driver").newInstance();
  				} catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
  						// TODO Auto-generated catch block
  						e.printStackTrace();
  				}
  			try {
  								con = DriverManager.getConnection("jdbc:mysql://localhost?autoReconnect=true&useSSL=false", "root", "12skdmsdn");
  				} catch (SQLException e) {
  						// TODO Auto-generated catch block
  						e.printStackTrace();
  						}
  				try {
  						if (!con.isClosed())
  								System.out.println("Successfully connected to MySQL server.");
  					} catch (SQLException e) {
  							// TODO Auto-generated catch block
  								e.printStackTrace();
  								}
	
  										Statement stmt = null;
  											try {
  													stmt = (Statement) con.createStatement();
  												} catch (SQLException e) {
  														// TODO Auto-generated catch block
  													e.printStackTrace();
  												}
  												try {
  															stmt.execute("use playinfo") ;
  													} catch (SQLException e) {
  															// TODO Auto-generated catch block
  															e.printStackTrace();
  														}
//===============================================//   
  							Storage [] pi = new Storage[7];
  							
  						 for( int i = 0; i < 7 ; i++)
						    {
  							 	pi[i] = new Storage();
					
						    }
  			
  							stmt.executeQuery("SELECT title,player,date,content FROM playinfo");
  						    ResultSet rs = stmt.getResultSet(); 		
  						
    				
    				
  						   
  						    for( int i = 0; rs.next() ; i++)
  						    {
  						    	pi[i].get_title(rs.getString("title"));
  						    	pi[i].get_player(rs.getString("player"));
  						    	pi[i].get_date(rs.getString("date"));
  						    	pi[i].get_content(rs.getString("content"));
  						    }
  						    
  						    rs.close();
  						    
  						  PlayList list = new PlayList(7);
  						  
  						for( int i =0 ; i<7 ; i++)
  						{
  							list.appendPlay(pi[i]);
  						}
  						
  						Iterator it = list.iterator();
  						
  					  String [][]  obj = new String[7][4];
  			        
  			        for( int i = 0 ; it.hasNext() ; i++)
  			    	{
  			    		 Storage play = (Storage)it.next();
  			    		 
  			    			obj[i][0] = play.return_title();
  			    			obj[i][1] = play.return_player();
  			    			obj[i][2] = play.return_date();
  			    			obj[i][3] = play.return_content();
  			    	}

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        bookBtn = new javax.swing.JButton();
        payBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
      
        
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(

        	
        	new Object[][]{
        		
        		{obj[0][0],obj[0][1],obj[0][2],obj[0][3]},
        		{obj[1][0],obj[1][1],obj[1][2],obj[1][3]},
        		{obj[2][0],obj[2][1],obj[2][2],obj[2][3]},
        		{obj[3][0],obj[3][1],obj[3][2],obj[3][3]},
        		{obj[4][0],obj[4][1],obj[4][2],obj[4][3]},
        		{obj[5][0],obj[5][1],obj[5][2],obj[5][3]},
        		{obj[6][0],obj[6][1],obj[6][2],obj[6][3]}
        		
        	
        	},
        		
           
            new String [] {
                "Title ", "Player", "Date", "Content"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Title ");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Player");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Date");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Content");
        }

        jLabel1.setText("연극선택");
        
        String item1 = pi[0].return_title()+"/"+pi[0].return_player()+"/"+pi[0].return_date()+"/"+pi[0].return_content();
        String item2 = pi[1].return_title()+"/"+pi[1].return_player()+"/"+pi[1].return_date()+"/"+pi[1].return_content();
        String item3 = pi[2].return_title()+"/"+pi[2].return_player()+"/"+pi[2].return_date()+"/"+pi[2].return_content();
        String item4 = pi[3].return_title()+"/"+pi[3].return_player()+"/"+pi[3].return_date()+"/"+pi[3].return_content();
        String item5 = pi[4].return_title()+"/"+pi[4].return_player()+"/"+pi[4].return_date()+"/"+pi[4].return_content();
        String item6 = pi[5].return_title()+"/"+pi[5].return_player()+"/"+pi[5].return_date()+"/"+pi[5].return_content();
        String item7 = pi[6].return_title()+"/"+pi[6].return_player()+"/"+pi[6].return_date()+"/"+pi[6].return_content();
        
        con.close();
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { item1,item2,item3,item4,item5,item6,item7}));

        bookBtn.setText("예약");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        payBtn.setText("뒤로가기");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
    	bookinginfo = jComboBox2.getSelectedItem().toString();
    	new Booking().setVisible(true);
        
    } 
    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
       this.setVisible(false);
       new HandongPlay().setVisible(true);
    }  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new PlayInfo().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bookBtn;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton payBtn;
    // End of variables declaration                   
}

